Proposed new flow/structure
axiom-crypto/axiom-quickstart pull request #7
Opened 2024-01-14 21:25 UTC by ytham

- fixes typescript compile and package issues
- `app/axiom/data/inputs.json` is default input (from new sdk-client CLI that checks if that file exists`
- circuit inputs use inputs.xxx variables

2024-01-14 21:57 UTC, yi-sun requested changes

2024-01-14 21:57 UTC, yi-sun commented on app/axiom/average.circuit.ts
>    const balances = await Promise.all(
We should avoid Promise.all since the order is not deterministic

2024-01-14 21:57 UTC, yi-sun commented on lib/axiom-v2-contracts
> +Subproject commit 52245e9a5445fc88258a54168728fb3ab4460561
Should remove this dependency entirely to only use axiom-v2-client

2024-01-14 21:57 UTC, yi-sun commented on package.json
> +    "@axiom-crypto/client": "link:../axiom-sdk-client/client/dist",
Remove this local patch

2024-01-15 17:17 UTC, ytham commented
I think the CI test is erroring due to the version check being only for one specific version: https://github.com/axiom-crypto/axiom-v2-client/blob/ff030872d7200cace1c9cb7ad5a028c1ade8a067/src/test/AxiomVm.sol#L274

we might want to consider just doing a loose version check or just a package existence check otherwise we might run into some issues down the line

2024-01-16 05:14 UTC, yi-sun approved these changes
LGTM

2024-01-16 05:14 UTC, merged